apiVersion: apps/v1
kind: Deployment # mainly used for horizontally scalable apps?
metadata:
  namespace: roles-ai-ns
  name: roles-ai-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roles-ai-api
  template:
    metadata:
      labels:
        app: roles-ai-api
    spec:
      containers:
        - name: roles-ai-api
          image: 448999958455.dkr.ecr.us-east-1.amazonaws.com/roles-ai-reg-priv1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health-check
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health-check
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 15
          env:
            - name: PORT
              value: "3000"
            - name: POSTGRES_HOST
              value: $(ROLES_AI_DB_SERVICE_SERVICE_HOST)
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: roles-ai-db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: OPENAI_KEY
              value: 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
