---
apiVersion: v1
kind: Service
metadata:
  name: eks-roles-ai-lb-service
  namespace: roles-ai-ns
  labels:
    app: roles-ai-api
spec:
  selector:
    app: roles-ai-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
