---
apiVersion: v1
kind: Service
metadata:
  name: roles-ai-api-service
  namespace: roles-ai-ns
  labels:
    app: roles-ai-api-service
spec:
  selector:
    app: roles-ai-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
