version: '3'
services:
  rolesai-dev-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rolesai-dev-db
    ports:
      - '5433:5432'
    volumes: 
      - rolesai-dev-db:/var/lib/postgresql/data

volumes:
  rolesai-dev-db:
    driver: local