---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roles-ai-db
spec:
  selector:
    matchLabels:
      app: roles-ai-db
  replicas: 1
  template:
    metadata:
      labels:
        app: roles-ai-db
    spec:
      containers:
        - name: roles-ai-db
          image: postgres:13
          ports:
            - containerPort: 5432
              name: "postgres"
          env:
            - name: POSTGRES_DB
              value: roles-ai-db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
