---
# db-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: roles-ai-db-service
spec:
  type: ClusterIP
  selector:
    app: roles-ai-db
  ports:
    - name: "postgres"
      protocol: TCP
      port: 5432
      targetPort: 5432
