apiVersion: v1
kind: Service
metadata:
  name: roles-ai-client-service-lb
spec:
  selector:
    app: roles-ai-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer