apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roles-ai-ns
  name: roles-ai-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roles-ai-client
  template:
    metadata:
      labels:
        app: roles-ai-client
    spec:
      containers:
        - name: roles-ai-client
          image: 448999958455.dkr.ecr.us-east-1.amazonaws.com/roles-ai-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
